name: Reusable Go Build

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Go application
        uses: ./.github/actions/go-build
        with:
          go-version: ${{ inputs.go-version }}
